import type { Metadata } from "next";
import React from "react";
import Link from "next/link";
import { StaticShell } from "@/components/shared/static-shell";
import { buildPageMetadata, siteConfig } from "@/lib/seo";

export const metadata: Metadata = buildPageMetadata({
  title: "Privacy Policy",
  description:
    "How GradGrid collects, uses, and protects your personal information. Your data's safety is our priority.",
  path: "/privacy",
  noIndex: true,
});

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-bold font-display text-ink mb-3">{title}</h2>
      <div className="space-y-3 text-sm text-mid leading-relaxed">{children}</div>
    </section>
  );
}

export default function PrivacyPage() {
  const { contact, legal } = siteConfig;

  return (
    <StaticShell
      eyebrow="Legal"
      title="Privacy Policy"
      subtitle={`This policy explains what information we collect through ${siteConfig.name}, how we use it, and the choices you have. Your trust matters to us.`}
    >
      <p className="text-xs text-mist mb-10">
        Last updated: {legal.privacyUpdatedAt}
      </p>

      <Section title="1. Information We Collect">
        <p>We collect information you provide directly and information generated by your use of the Service:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            <strong className="text-ink">Account information</strong> — your name, email address,
            password (stored securely), and the institution you belong to.
          </li>
          <li>
            <strong className="text-ink">Institution data</strong> — information about students,
            staff, attendance, examinations, and fees that you or your institution enters into the
            platform.
          </li>
          <li>
            <strong className="text-ink">Usage information</strong> — how you interact with the
            Service, such as pages visited and features used, to help us improve it.
          </li>
          <li>
            <strong className="text-ink">Device information</strong> — browser type, device type,
            and IP address for security and diagnostic purposes.
          </li>
        </ul>
      </Section>

      <Section title="2. How We Use Your Information">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>To provide, maintain, and improve the Service;</li>
          <li>To authenticate you and keep your account secure;</li>
          <li>To generate reports and insights you request;</li>
          <li>To communicate with you about the Service, updates, and support;</li>
          <li>To detect, prevent, and address technical or security issues.</li>
        </ul>
        <p>
          We never sell your personal information or your institution&rsquo;s data to anyone.
        </p>
      </Section>

      <Section title="3. Data Storage & Security">
        <p>
          Your data is stored securely in the cloud with encryption in transit and at rest.
          Sensitive fields are additionally encrypted at the application layer. Access is
          restricted by role, and all privileged actions are recorded in audit logs. While no
          system is perfectly secure, we apply industry-standard safeguards to protect your
          information.
        </p>
      </Section>

      <Section title="4. Cookies & Local Storage">
        <p>
          We use cookies and local storage to keep you signed in, remember your preferences (such
          as theme), and understand how the Service is used. You can control cookies through your
          browser settings; some features may not work as intended if you disable them.
        </p>
      </Section>

      <Section title="5. Sharing of Information">
        <p>
          We do not share your personal information with third parties except:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>With service providers who help us operate the Service (e.g., hosting), under strict confidentiality obligations;</li>
          <li>When required by law, regulation, or legal process;</li>
          <li>With your consent or at your direction.</li>
        </ul>
      </Section>

      <Section title="6. Data Retention">
        <p>
          We retain your information for as long as your account is active and for a reasonable
          period afterward to meet legal and operational obligations. You may request deletion of
          your account and data at any time, and we will honor such requests in accordance with
          applicable law.
        </p>
      </Section>

      <Section title="7. Your Rights">
        <p>
          Depending on your location, you may have the right to access, correct, or delete your
          personal information, and to object to or restrict certain processing. To exercise any
          of these rights, contact us at {contact.supportEmail}.
        </p>
      </Section>

      <Section title="8. Children's Privacy">
        <p>
          {siteConfig.name} is intended for use by educational institutions and their staff. Where
          student data is processed, it is done so under the direction and control of the
          institution, which is responsible for obtaining any necessary consents.
        </p>
      </Section>

      <Section title="9. Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. We will notify you of material
          changes through the Service or by email. The &ldquo;last updated&rdquo; date above reflects the most
          recent revision.
        </p>
      </Section>

      <Section title="10. Contact Us">
        <p>
          If you have questions about this Privacy Policy or how we handle your data, contact us
          at{" "}
          <a href={`mailto:${contact.email}`} className="text-brand hover:underline">
            {contact.email}
          </a>{" "}
          or by mail at {contact.address}, {contact.city}, {contact.state}, {contact.country}. See
          our <Link href="/contact" className="text-brand hover:underline">Contact page</Link> for
          more ways to reach us.
        </p>
      </Section>
    </StaticShell>
  );
}
